### PR TITLE
Fix availability issue for mini

### PR DESCRIPTION
**Pull request by unDemian**
**Pull request recommendations:**
Fixes https://github.com/home-assistant/core/issues/93976 by porting https://github.com/vangorra/python_gogogate2_api/commit/e4b8e5ea65be6bcb38a3cc54e5a5b1bc2201aa28 from https://github.com/vangorra/python_gogogate2_api

### CODE REVIEW

**Comment by bdraco** [comment]
@unDemian Tests are failing, please check

**Review by bdraco — APPROVED** [review]

**Comment by bdraco** [comment]
https://pypi.org/project/ismartgate/5.0.1/

**Comment by bdraco** [comment]
You'll have to bump the lib in HA as well

**Comment by unDemian** [comment]
Will do, thanks

**Comment by unDemian** [comment]
https://github.com/home-assistant/core/pull/100636

**Pull request merged**
